### ISSUE TITLE
Question Plex

### ISSUE THREAD

**Issue by berot3** [BlkChockr/nzbget-stream#1]
Before I try this out I wanted to ask, whether it is possible to combine this with Plex?

So instead of opening the file with a video-player (which is not possible on a headless server) it should inform Plex about the new file. I also don't know if Plex is able to handle a always changing file...

**Comment by c4tz** [comment]
Sorry, I'm currently on vacation, so response times may vary.

I have not worked with Plex yet and can't try it at the moment, but you could just test it by editing line 116 to make it inform Plex.. ;)

**Comment by c4tz** [comment]
Just to make this clear: "Vacation" means that I'm gonna travel around the world for 8 months. So I probably won't do this in the near future :)

**Comment by c4tz** [comment]
Closing this for now, reopen if you still need advice.

**Comment by berot3** [comment]
thx
