### ISSUE TITLE
Video Stops After Each New RAR

### ISSUE THREAD

**Issue by wtf911** [BlkChockr/nzbget-stream#4]
I know you said it was only tested using VLC but the main player I use is MPHC (Media Player Home Classic) and the issue that happens is when a new file finishes and is appended to the extracted movie it throws off the playback, in my case causing the video to start over in MPHC. I'm not sure how to better explain it...

I monitored the extracted file in Windows explorer and continuously refreshed to see the file size and how it correlated to when MPHC starts over. For example, let's say the total video is 15GB and it's partially downloaded. Let's say the extracted file is 5.0GB in Windows, I start it playing in MPHC, as I hit refresh I see it change to saying 15GB in Windows, it is still playing fine in MPHC, then all of a sudden it starts over in MPHC and in Windows it might show 5.1GB ...so to me it seems each time a new .rar file finishes and gets added it causes playback to start over. Any ideas how to resolve or workaround this? Thank you!

**Comment by c4tz** [comment]
Do you experience the same problem when using VLC? 

I'm just trying to figure out if its Windows or MPHC causing the trouble here. When it is MPHC causing this behavior, I probably won't be able to help you with this.

You could then only install VLC and let nzbget-stream open the video files with it, while keeping MPHC as your main player.

This would be done by changing [line 116](https://github.com/BlkChockr/nzbget-stream/blob/master/stream.py#L116) to:

```
subprocess.call(('PATHTOVLC.EXE', filePath))
```

**Comment by wtf911** [comment]
I tested it with VLC and it did the same thing...MPHC it starts the video over, VLC it just stops playing. This is after each RAR finishes. But I realized it is specific to the NZB I was using. It did not create a "stream" file like it did when I tried another NZB. Here is the one which gave me trouble:

[Removed: Please do not post copyrighted Material]

(You should be able to download it.)

It seems the video is very deeply nested inside a few folders. Perhaps that is what caused the problem. Maybe you will be able to come up with a fix?

**Comment by wtf911** [comment]
Also this might be of some use, this is from my log:

```
DETAIL	Writing articles for [Removed: Please do not post copyrighted Material]
INFO	Successfully downloaded [Removed: Please do not post copyrighted Material]
DETAIL	Executing queue-script Stream.py for [Removed: Please do not post copyrighted Material]
INFO	Stream: Traceback (most recent call last):
INFO	Stream:   File "C:\ProgramData\NZBGet\scripts\Stream.py", line 144, in <module>
INFO	Stream:     main()
INFO	Stream:   File "C:\ProgramData\NZBGet\scripts\Stream.py", line 138, in main
INFO	Stream:     os.rename(videoPath, STREAM_FILE)
INFO	Stream: WindowsError: [Error 3] The system cannot find the path specified
```

**Comment by c4tz** [comment]
> It seems the video is very deeply nested inside a few folders. Perhaps that is what caused the problem. Maybe you will be able to come up with a fix?

I'll have a look into it after the weekend, but I think I remember testing that case, too.

PS: I removed your link and NZB name; Please do not post copyrighted Material.

**Comment by wtf911** [comment]
Okay. Sorry about that. Thank you for the help. I would donate if you had a way of accepting.

**Comment by c4tz** [comment]
I wrote the script for myself initially and still use it, so there's no need for donation, but thank you for the offer :)

I think I fixed your problem, could you please test it with the current version?

Heres the diff: https://github.com/BlkChockr/nzbget-stream/commit/7161ff5ee9c3b40f81b5ee618c5e25d4077643f5

**Comment by wtf911** [comment]
You did it! I retested with the one I was having a problem with and it works perfectly now. :) Thank you again for the help.
