### ISSUE TITLE
Possible to run on androidtv?

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [BlkChockr/nzbget-stream#5]
Hey. Did you think it is possible to run your nzbget script on termux, on a nvidia shieldTV?

My main goal is a setup that can stream nzb-dl's to kodi.

Greetings by SUIAT

**Comment by c4tz** [comment]
This will most certainly not be possible. Cited from [here](https://nzbget.net/installation-on-android):

```
Post-processing scripts

Most scripts are written in Python. Unfortunately there is no Python for Android. That means most scripts will not work.
```

Closing this issue for now, feel free to reopen in the future when there is a solution for python-scripts from nzbget :)
